[build]
  base = "frontend"
  publish = "out"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://oragnisation-du-travail.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://oragnisation-du-travail.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
