[build]
  base = "frontend"
  publish = "frontend/.next"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://your-backend-url.onrender.com"

# Configuration pour Next.js sur Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
