# Generated by Django 5.0.6 on 2025-10-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_event_schedule'),
    ]

    operations = [
    ]
