# Generated by Django 5.0.6 on 2025-10-20 19:39

from django.db import migrations, models
from django.utils import timezone


def add_created_at_default(apps, schema_editor):
    """Ajoute une valeur par défaut pour created_at sur les TimeEntry existantes"""
    TimeEntry = apps.get_model('work', 'TimeEntry')
    default_time = timezone.now()
    for entry in TimeEntry.objects.all():
        if not hasattr(entry, 'created_at') or entry.created_at is None:
            entry.created_at = entry.started_at or default_time
            entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20251020_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='created_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.RunPython(add_created_at_default, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='timeentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
